### ISSUE TITLE
Extension puts a heavy load on the CPU

### ISSUE THREAD

**Issue by mkoculak** [alexkainzinger/resource-watchdog#2]
Hi,
first of all, I really like the extension - tried a couple of different ones and yours works the best for me, thanks!

I have recently noticed, that on my medium-aged machine, but with good specs, activating the extension puts a serious amount of load on the CPU.
On the image below you can see extension on 2000 ms refresh and then changed to 20000 ms.
![system monitor](https://user-images.githubusercontent.com/16628635/194046854-ca585952-2f6a-4a57-ab8a-c0a11ee2181f.png)

I am not sure if this behavior was there all the time, just noticed it after recent big update for Windows 11, where my computer started to slow down. Not saying its because of the extension, but this CPU usage pattern seemed like something that maybe is not intentional and can be somehow reduced?

**Comment by alexkainzinger** [comment]
Hi! Thanks for the nice feedback.

Can you maybe list the stats you have enabled in the config?

I was thinking that maybe some stats could be refreshed less frequently (Disk, Uptime) by default (like once every minute, or configurable) and the ones that should be updated more frequently (CPU, RAM, GPU) are configureable anyways with `updateFrequencyMs`.

As I rely on a 3rd party library for reading the stats, I might also update it and give it a test. I also have a PC running the 8700k with Win11, so I could also give it a try 😄

**Comment by mkoculak** [comment]
Hey,
so I think I had the default things enabled: CPU load, CPU freq, and Memory usage.
Update frequency was 2000ms.

But your comment prompted me to test each of the settings individually and I found the main culprit - Battery setting was turned on by default (its a PC, so no battery). When I turned it off, ~80% of load from your extension dropped.
The rest still generates a noticeable activity, but way less then before.

**Comment by alexkainzinger** [comment]
This is a pretty interesting finding with the battery settings. I will check myself and try to fix/optimize this! thx for checking

**Comment by alexkainzinger** [comment]
Seems like the battery check is pretty expensive. I published a new version (1.2.0) that fixes this issue and also disables battery indicator by default as I think this extension is mainly used on desktop PCs.

Can you please check if it also works better for you now? I see a pretty big reduction in load with the new version on my 8700k

**Comment by mkoculak** [comment]
Yes, the load dropped by more than a half.
I also checked out similar extensions to see if they generate such load and it seems they must be using some other mechanisms to get the data as they don't exhibit this pattern.

Still, thanks a lot for your work!!
